name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  publish:
    name: Publish to npm
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest # npm >=11.5.1 required for trusted publishing
      - run: npm ci
      - run: npm publish --provenance --access public
